# Site settings
title: Jimil Patel
email: jimilp7@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jimilp7.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Minima theme settings
header_pages: []

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jimil"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE 